#pragma once

#define MIN_MENU_CHOICES 1
#define MAIN_MENU_MAX_CHOICES 3
#define CITY_MENU_MAX_CHOICES 3
#define CINEMA_MENU_MAX_CHOICES 4
#define HALL_MENU_MAX_CHOICES 4
#define PROJECTION_MENU_MAX_CHOICES 4

#define MAX_PROJECTION_SIZE 15

#define SEAT_PLAN_ROWS 10
#define SEAT_PLAN_COLS 10

#define PLATINUM_SEAT_PRICE 25.00
#define GOLD_SEAT_PRICE 22.00
#define SILVER_SEAT_PRICE 17.00

#define PLATINUM_SEAT_ROW_LIMIT 2
#define GOLD_SEAT_ROW_LIMIT 5