#pragma once

#define MIN_MENU_CHOICES 1
#define MAIN_MENU_MAX_CHOICES 2
#define CITY_MENU_MAX_CHOICES 3
#define CINEMA_MENU_MAX_CHOICES 4
#define HALL_MENU_MAX_CHOICES 4
#define PROJECTION_MENU_MAX_CHOICES 4

#define MAX_PROJECTION_SIZE 15

#define SEAT_PLAN_ROWS 10
#define SEAT_PLAN_COLS 10